apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efk-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sujitmendhe/google-store-DevOps-project.git
    path: efk-stack
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-logging
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
